# Generated by Django 2.1 on 2019-07-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190630_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='shipping_address',
        ),
    ]
