# Generated by Django 2.1 on 2019-06-04 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190604_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
