# Generated by Django 2.1 on 2019-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_score',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
