# Generated by Django 2.1 on 2019-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190513_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
